---
name: kubernetes-deploy
up:
  - ruby: 2.3.2
  - bundler
  - minikube

minikube: {}

commands:
  test:
    run: bundle exec rake test
  tophat:
    run: PRINT_LOGS=1 bundle exec ruby -I test test/integration/kubernetes_deploy_test.rb -n/${1}/
    desc: Tophat a change by running a test scenario with logging output enabled.
    syntax:
      optional:
        argument: TEST_REGEX
